name: rpgmv-dev-notes
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.vercel_token }} # Required
          vercel-org-id: ${{ secrets.vercel_orgId}} #Required
          vercel-project-id: ${{ secrets.vercel_projectId}} #Required
          vercel-version: 34.1.2
          vercel-args: "--prod --cwd ./ --local-config ./docs/rpgmv-dev-notes/vercel.json"
          # working-directory: ./docs/rpgmv-dev-notes
          # 考虑不再主动部署到此路径 该路径预期被 cloudflare 实现域名重定向
          # www.ruan-cat.com
          alias-domains: |
            rpgmv-dev-notes.ruancat6312.top
            rpgmv-dev-notes.ruan-cat.com
