name: ruan-cat-notes
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.vercel_token }} # Required
          vercel-org-id: ${{ secrets.vercel_orgId}} #Required
          vercel-project-id: ${{ secrets.vercel_projectId}} #Required
          vercel-version: 34.1.2
          vercel-args: "--prod"
          working-directory: ./docs/ruan-cat-notes
          alias-domains: |
            ruan-cat-notes.ruancat6312.top
            ruan-cat-notes.ruan-cat.com
            notes.ruan-cat.com
