name: 测试合并的工作流行为
on:
  push:
    branches:
      - monorepo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出分支
        uses: actions/checkout@main

      - name: 部署笔记项目
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.vercel_token }} # Required
          vercel-org-id: ${{ secrets.vercel_orgId}} #Required
          vercel-project-id: ${{ secrets.vercel_projectId}} #Required
          vercel-version: 34.1.2
          vercel-args: "--prod --cwd ./ --local-config ./docs/ruan-cat-notes/vercel.json"
          alias-domains: |
            ruan-cat-notes.ruancat6312.top
            ruan-cat-notes.ruan-cat.com
            notes.ruan-cat.com

      - name: 部署rmmv项目
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.vercel_token }} # Required
          vercel-org-id: ${{ secrets.vercel_orgId}} #Required
          vercel-project-id: ${{ secrets.vercel_projectId}} #Required
          vercel-version: 34.1.2
          vercel-args: "--prod --cwd ./ --local-config ./docs/rpgmv-dev-notes/vercel.json"
          alias-domains: |
            rpgmv-dev-notes.ruancat6312.top
            rpgmv-dev-notes.ruan-cat.com
