name: 部署文档项目

env:
  # vercel的token
  vct: ${{ secrets.vercel_token }}

  # 从教程内得知 环境变量名称必须大写
  VERCEL_ORG_ID: ${{ secrets.vercel_orgId }}
  VERCEL_PROJECT_ID: ${{ secrets.vercel_projectId }}

  # vercel项目名称
  pjn: rpgmv-dev-notes-betd

  # 项目路径
  notesPath: ./docs/ruan-cat-notes
  rmmvPath: ./docs/rpgmv-dev-notes

  # 笔记项目 url
  notesUrl1: notes.ruan-cat.com
  notesUrl2: ruan-cat-notes.ruan-cat.com
  notesUrl3: ruan-cat-notes.ruancat6312.top

  # rmmv项目 url
  rmmvUrl1: rpgmv-dev-notes.ruancat6312.top
  rmmvUrl2: rpgmv-dev-notes.ruan-cat.com

on:
  push:
    branches:
      # - monorepo
      - main-notuse

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出分支
        uses: actions/checkout@main

      - name: 开启 corepack
        run: corepack enable && corepack install

      - name: 检查pnpm版本
        run: pnpm -v

      - name: 安装整个项目的依赖
        run: pnpm i

      - name: 用npm安装vercel cli工具
        run: npm i -g vercel@latest

      - name: 检查vercel cli版本
        run: vc -v

      - name: 各子项目连接现有的vercel项目
        run: |
          vc link --yes --cwd=${{env.notesPath}} --project=${{env.pjn}} -t ${{env.vct}}
          vc link --yes --cwd=${{env.rmmvPath}} --project=${{env.pjn}} -t ${{env.vct}}

      - name: vercel生成特定.vercel/output/static目录
        run: |
          vc build --yes --prod --cwd=${{env.notesPath}} -A ./vercel.null.json -t ${{env.vct}}
          vc build --yes --prod --cwd=${{env.rmmvPath}} -A ./vercel.null.json -t ${{env.vct}}

      - name: turbo并发打包全部子项目
        run: pnpm run on-github-action-flow

      - name: 各子项目上传文件并部署到vercel内
        run: |
          notesTempUrl="$(vc deploy --yes --prebuilt --prod --cwd=${{env.notesPath}} -t ${{env.vct}})"
          vc alias -t ${{env.vct}} set "$notesTempUrl" ${{env.notesUrl1}} 
          vc alias -t ${{env.vct}} set "$notesTempUrl" ${{env.notesUrl2}}
          vc alias -t ${{env.vct}} set "$notesTempUrl" ${{env.notesUrl3}}

          rmmvTempUrl="$(vc deploy --yes --prebuilt --prod --cwd=${{env.rmmvPath}} -t ${{env.vct}})"
          vc alias -t ${{env.vct}} set "$rmmvTempUrl" ${{env.rmmvUrl1}}
          vc alias -t ${{env.vct}} set "$rmmvTempUrl" ${{env.rmmvUrl2}}
